apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-mikrofrontend-selector
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  prometheus:
    path: /metrics
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 100
  ingresses:
    - "https://tms-mikrofrontend-selector.nav.no"
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side-proxy
    outbound:
      rules:
        - application: meldekort-api
          namespace: meldekort
        - application: veilarboppfolging
          namespace: pto
          cluster: prod-fss
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
      external:
        - host: "safselvbetjening.prod-fss-pub.nais.io"
  gcp:
    sqlInstances:
      - name: microfrontend
        type: POSTGRES_14
        tier: db-custom-1-4096
        diskType: SSD
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: microfrontends
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
    buckets:
      - name: microfrontend-manifest-prod
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 128Mi
  env:
    - name: GROUP_ID
      value: tms-mikrofrontend-selector-01
    - name: RAPID_TOPIC
      value: min-side.aapen-microfrontend-v1
    - name: STORAGE_BUCKET_NAME
      value: microfrontend-manifest-prod
    - name: SAF_URL
      value: https://safselvbetjening.prod-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: prod-fss:teamdokumenthandtering:safselvbetjening
    - name: AIA_API_URL
      value: http://aia-backend.paw
    - name: AIA_CLIENT_ID
      value: prod-gcp:paw:aia-backend
    - name: OPPFOLGING_API_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging
    - name: OPPFOLGING_CLIENT_ID
      value: prod-fss:pto:veilarboppfolging
    - name: MELDEKORT_BASE_URL
      value: http://meldekort-api.meldekort/meldekort/meldekort-api
    - name: MELDEKORT_CLIENT_ID
      value: prod-gcp:meldekort:meldekort-api
    - name: PDL_API_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_API_CLIENT_ID
      value: "prod-fss:pdl:pdl-api"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B328"
