apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-mikrofrontend-selector
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-mikrofrontend-selector-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  prometheus:
    path: /metrics
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 100
  ingresses:
    - "https://tms-mikrofrontend-selector.nav.no"
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side-proxy
  gcp:
    sqlInstances:
      - name: microfrontend
        type: POSTGRES_14
        tier: db-custom-1-4096
        diskType: SSD
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: microfrontends
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 256Mi
