apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-mikrofrontend-selector
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 5
  prometheus:
    path: /metrics
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 100
  ingresses:
    - "https://tms-mikrofrontend-selector.nav.no"
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side-proxy
  gcp:
    sqlInstances:
      - name: microfrontend
        type: POSTGRES_14
        tier: db-custom-1-4096
        diskType: SSD
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: microfrontends
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
    buckets:
      - name: microfrontend-manifest-prod
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 128Mi
  env:
    - name: GROUP_ID
      value: tms-mikrofrontend-selector-01
    - name: RAPID_TOPIC
      value: min-side.aapen-microfrontend-v1
    - name: STORAGE_BUCKET_NAME
      value: microfrontend-manifest-prod
