# Forutsetter at min-side-repo-authenticator er installert i repoet
# og at PRIVATE_KEY og APP_ID (disse får du fra min-side)  ligger som action-secrets i repoet

name: Update microfrontend-manifest
on: <ønsket hook>

jobs:
  secrets: inherit
  trigger_manifest_update:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    with:
      cluster: "<cluster: dev-gcp eller prod-gcp>"
      id: "<mikrofrontend-id>"
      url: "<url til js-fil>"


    cdn_upload_and_update:
      #legg inn etter build-steps
      - steps:
          - name: cdn-upload
            uses: navikt/frontend/actions/cdn-upload/v1@main
            with:
              cdn-team-name: <team-navn>
              source: ./dist/
              destination: <dest for ditt team>
          - name: export-cdn-url
            run: |
              paths="${{ steps.cdn-upload.outputs.uploaded }}"
              cdn_js_path=$(echo $paths | cut -d',' -f1)
              echo "url=https://cdn.nav.no/$cdn_js_path" >> $GITHUB_OUTPUT
          - name: "update min-side-dev-manifest"
            uses: "navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main"
            with:
              cluster: <dev-gcp eller prod-gcp>
              id: <mikrofrontend-id>
              url: ${{ steps.export-cdn-url.outputs.url }}
