# Forutsetter at min-side-repo-authenticator er installert i repoet
# og at PRIVATE_KEY og APP_ID (disse får du fra min-side)  ligger som action-secrets i repoet

name: Update microfrontend-manifest
on: <ønsket hook>

jobs:
  trigger_manifest_update:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    with:
      cluster: "<cluster: dev-gcp eller prod-gcp>"
      id: "<mikrofrontend-is>"
      url: "<url til nytt manifest>"
    secrets: inherit
