name: Update microfrontend-manifest

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'cluster manifestet skal oppdateres i'
        required: true
        type: string
      id:
        description: 'microfrontendId'
        required: true
        type: string
      url:
        description: 'url til nytt manifest i cdn'

jobs:
  update-dev-manifest:
    runs-on: ubuntu-latest
    if: ${{ inputs.cluster}} == 'dev-gcp'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY_DEV }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Lag testfil'
        run: echo 'Testing testing' > testing.txt
      - name: 'Last opp til bucket'
        run: gcloud storage cp testing.txt gs://microfrontend-manifest-dev
      - name : 'Les fil'
        run: gcloud storage cp gs://microfrontend-manifest-dev/testing.txt testing2.txt && cat testing2.txt

               





