name: Update microfrontend-manifest

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'cluster manifestet skal oppdateres i'
        required: true
        type: string
      id:
        description: 'microfrontendId'
        required: true
        type: string
      url:
        description: 'url til nytt manifest i cdn'

jobs:
  update-dev-manifest:
    runs-on: ubuntu-latest
    if: ${{ inputs.cluster}} == 'dev-gcp'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY_DEV }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Henter manifestfil'
        run:  gcloud storage cp gs://microfrontend-manifest-dev/manifests.json manifests.json
      - name : 'oppdater fil'
        run:  python3 update-manifests.py ${{ inputs.id }} ${{ inputs.url }}
      - name: 'Last opp til bucket'
        run: gcloud storage cp manifests.json gs://microfrontend-manifest-dev

               





